/*
 * Model for object: Class03.
 *
 * NOTE: This class is auto generated by YModeL (https://github.com/Zhykos/YModeL).
 * Do not edit this class manually.
 */

export abstract class Class03 {

    field01: number;

    field02: string;

}
