openapi: "3.0.3"
info:
  version: 1.0.0
  title: YModeL OpenAPI
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
tags:
- name: metamodel
  description: All services to manipulate metamodels
  externalDocs:
    description: Definition of metamodeling
    url: https://en.wikipedia.org/wiki/Metamodeling
paths:
  /metamodel/generate:
    post:
      summary: Generate metamodel
      description: Generate a metamodel from a file into a selected language
      operationId: generateMetamodel
      tags:
        - metamodel
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                language:
                  $ref: "#/components/schemas/Language"
                file:
                  type: string
                  description: metamodel yaml declaration file to upload
                  format: binary
      responses:
        '200':
          description: A zip file containing the generated metamodel
          content:
            application/zip:    
              schema:
                type: string
                format: binary
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Language:
      type: object
      description: Target language
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the language
          enum:
            - typescript
    Error:
      type: object
      description: API error
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string